apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template: # blueprint for pods
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: webapp
          image: aallal18032000/express:v0.8.3
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-pwd
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-url
          
      
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  type: LoadBalancer #To make it an external service, we put NodePort ( instead of clusterIp which is the type of an internal service )
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 #Port of the pods
      nodePort: 30300 #Open the port of a node
